# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "58723083e4f529db3116918a098d957f"
name = "tbi-concept-app"
application_url = "https://tbi-concept-app.onrender.com"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
scopes = "read_products,write_products,read_themes,write_themes"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
